src/functionalTest/resources/scenarios/ia/IA-RIA-4605-moveToPaymentPending-terminates-reviewTheAppeal.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6374-changeHearingCentre-reconfigure-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6374-editAppealAfterSubmit-reconfigure-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6717-ada-submitAppeal-with-appealSubmitted-postEventState-should-create-a-task.json, src/functionalTest/resources/templates/ia/ccd/minimal-appeal-started.json
https://tools.hmcts.net/jira/browse/RIA-6717
Added FT test for ada review the appeal task
```
[ ] Yes
[ x ] No
```
=> RIA-6717 Added FT test for ada review the appeal task

Jenkinsfile_CNP, Jenkinsfile_nightly, src/functionalTest/resources/scenarios/ia/IA-RIA-6714-ada-adjourn-makeAnApplication-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6714-ada-expedite-makeAnApplication-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6714-ada-judge-review-application-decision-makeAnApplication-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6714-ada-link-unlink-appeals-makeAnApplication-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6714-ada-other-makeAnApplication-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6714-ada-reinstate-an-ended-appeal-makeAnApplication-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6714-ada-time-extension-makeAnApplication-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6714-ada-update-appeal-details-makeAnApplication-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6714-ada-update-hearing-requirements-makeAnApplication-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6714-ada-withdraw-makeAnApplication-should-create-a-task.json, src/testUtils/java/uk/gov/hmcts/reform/wapostdeploymentfttests/services/AuthorizationHeadersProvider.java
https://tools.hmcts.net/jira/browse/RIA-6714
Added ADA - Make an Application tasks for LO and Judge
```
[ ] Yes
[ x ] No
```
=> Ria 6714 add ada process application ft tests

src/functionalTest/resources/scenarios/ia/IA-RIA-6725-ada-changeDirectionDueDate-should-create-a-followup-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6725-ada-removeLegalRepresentative-should-create-a-followup-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6725-ada-removeRepresentation-should-create-a-followup-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6725-ada-requestCaseBuilding-with-caseBuilding-postEventState-should-create-a-followup-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6725-ada-requestRespondentEvidence-with-awaitingRespondentEvidence-postEventState-should-create-a-followup-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6725-ada-requestRespondentReview-with-respondentReview-postEventState-should-create-a-followup-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6725-ada-sendDirection-should-create-a-followup-task.json
https://tools.hmcts.net/jira/browse/RIA-6725
Added  ADA follow up tasks
```
[ ] Yes
[ x ] No
```
=> RIA-6725 Added FT tests for ada follow-up tasks

src/functionalTest/resources/scenarios/ia/IA-RIA-6725-ada-changeDirectionDueDate-should-create-a-followup-task.json
https://tools.hmcts.net/jira/browse/RIA-6725
Updated permissions for adaFollowUpExtendedDirection task
```
[ ] Yes
[ x ] No
```
=> RIA-6725 Update permissions for adaFollowUpExtendedDirection task

src/functionalTest/resources/scenarios/ia/IA-RIA-6724-ada-buildCase-with-caseUnderReview-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6724-ada-submitCase-with-caseUnderReview-postEventState-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-6724
-Add functional test for submitCase and buildCase
```
[ ] Yes
[X] No
```
=> RIA-6724-add-ada-when-submit-build-case-ft-test

src/functionalTest/resources/scenarios/ia/IA-RIA-6722-ada-uploadAdditionalEvidence-with-caseUnderReview-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6722-ada-uploadAdditionalEvidence-with-prepareForHearing-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6722-ada-uploadAdditionalEvidence-with-respondentReview-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6722-ada-uploadAdditionalEvidenceHomeOffice-with-caseBuilding-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6722-ada-uploadAdditionalEvidenceHomeOffice-with-caseUnderReview-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6722-ada-uploadAdditionalEvidenceHomeOffice-with-prepareForHearing-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6722-ada-uploadAdditionalEvidenceHomeOffice-with-respondentReview-postEventState-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-6722
Added functional tests for ADA upload additional evidence tasks
```
[ ] Yes
[ x ] No
```
=> RIA-6722 Added ADA upload additional evidence tasks FTs

src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidence-with-decided-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidence-with-decision-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidence-with-preHearing-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceAdminOfficer-with-decided-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceAdminOfficer-with-decision-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceAdminOfficer-with-preHearing-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceHomeOffice-with-decided-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceHomeOffice-with-decision-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceHomeOffice-with-preHearing-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceLegalRep-with-decided-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceLegalRep-with-decision-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceLegalRep-with-preHearing-postEventState-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-6726
-add ADA when review addendum evidence
```
[ ] Yes
[X] No
```
=> RIA 6726 add ADA when review addendum evidence

src/functionalTest/resources/scenarios/ia/IA-RIA-6799-ada-uploadHomeOfficeBundle-with-awaitingRespondentEvidence-postEventState-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-6799
-Add ADA when upload home office bundle
```
[ ] Yes
[X] No
```
=> RIA-6799-add-ada-when-upload-home-office-bundle

src/functionalTest/resources/scenarios/ia/IA-RIA-6732-ada-transferOutOfAdal-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-6732
Added FT for transfer out of ada task
```
[ ] Yes
[ x ] No
```
=> RIA-6732 Added transfer out of ADA task functional test

src/functionalTest/resources/scenarios/ia/IA-RIA-6727-ada-generateDecisionAndReasons-with-decision-postEventState-should-create-a-task.json
Added FT for Generate Decision And Reasons task
https://tools.hmcts.net/jira/browse/RIA-6727
```
[ ] Yes
[ x ] No
```
=> RIA-6727 Added FT for Generate Decision And Reasons task

src/functionalTest/resources/scenarios/ia/IA-RIA-6728-ada-applyForFTPAAppellant-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6728-ada-applyForFTPARespondent-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-6728
-add ADA when apply ftpa appellant respondent
```
[ ] Yes
[X] No
```
=> RIA 6728 add ada when apply ftpa appellant respondent

src/functionalTest/resources/scenarios/ia/IA-RIA-6731-adaSuitabilityReview-with-respondentReview-postEventState-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-6731
Added FT for adaSuitabilityReview event task
```
[ ] Yes
[ x ] No
```
=> RIA-6731 Added adaSuitabilityReview event task

src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidence-with-decided-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidence-with-decision-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidence-with-preHearing-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceAdminOfficer-with-decided-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceAdminOfficer-with-decision-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceAdminOfficer-with-preHearing-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceHomeOffice-with-decided-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceHomeOffice-with-decision-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceHomeOffice-with-preHearing-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceLegalRep-with-decided-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceLegalRep-with-decision-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6726-ada-uploadAddendumEvidenceLegalRep-with-preHearing-postEventState-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-6726
-Update the FT when add the judge permission for hearing judge
```
[ ] Yes
[X] No
```
=> RIA 6726 add when review addendum evidence v2

src/functionalTest/resources/scenarios/ia/IA-RIA-6729-ada-uploadHomeOfficeAppealResponse-with-respondentReview-postEventState-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-6729
Added uploadHomeOfficeAppealResponse event task FT
```
[ ] Yes
[ x ] No
```
=> RIA-6729 Added uploadHomeOfficeAppealResponse event task FT

src/functionalTest/resources/scenarios/ia/IA-RIA-6832-ada-decisionAndReasonsStarted-with-decision-postEventState-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-6832
add ADA when decision reasons started
```
[ ] Yes
[X] No
```
=> RIA-6832 add ADA when decision reasons started

src/functionalTest/resources/scenarios/ia/IA-RIA-6828-ada-decideAnApplication-with-adjourn-application-type-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-6828
Added execute permission to LO for adaEditListing
```
[ ] Yes
[ x ] No
```
=> RIA-6828 Added execute permission to LO for adaEditListing

src/functionalTest/resources/scenarios/ia/IA-RIA-6835-ada-submitAppeal-with-appealSubmitted-postEventState-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-6835
Added FT for adaAllocateHearingJudge task for ADA submitAppeal
```
[ ] Yes
[ x ] No
```
=> RIA-6835 Added adaAllocateHearingJudge task for ADA submitAppeal FT

src/functionalTest/resources/scenarios/ia/IA-RIA-6829-ada-listCase-with-prepareForHearing-postEventState-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-6829
-Add FT for ADA list case when create hearing bundle
```
[ ] Yes
[X] No
```
=> Ria 6829 add ada list case when create hearing bundle

src/functionalTest/resources/scenarios/ia/IA-RIA-6833-ada-listCase-with-awaitingRespondentEvidence-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-6833
Added FT test adaUploadHearingRecording task for ADA listCase event
```
[ ] Yes
[ x ] No
```
=> RIA-6833 Added FT for adaUploadHearingRecording task for ADA listCase

src/functionalTest/resources/scenarios/ia/IA-RIA-6831-ada-customiseHearingBundle-with-finalBundling-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6831-ada-generateHearingBundle-with-finalBundling-postEventState-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-6831
-add FT of ADA  when generate customise hearing bundle
```
[ ] Yes
[X] No
```
=> RIA 6831 add ADA when generate customise hearing bundle

src/functionalTest/resources/scenarios/ia/IA-RIA-6834-ada-changeHearingCentre-with-awaitingRespondentEvidence-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6834-ada-changeHearingCentre-with-caseBuilding-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6834-ada-changeHearingCentre-with-caseUnderReview-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6834-ada-changeHearingCentre-with-decision-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6834-ada-changeHearingCentre-with-finalBundling-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6834-ada-changeHearingCentre-with-preHearing-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6834-ada-changeHearingCentre-with-prepareForHearing-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6834-ada-changeHearingCentre-with-respondentReview-postEventState-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-6834
-add FT for ADA flag when change hearing centre
```
[ ] Yes
[X] No
```
=> RIA-6834 add ADA when change hearing centre

src/functionalTest/resources/scenarios/ia/IA-RIA-6964-applyForFTPAAppellant-should-create-adaAllocateFTPAJudge.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6964-applyForFTPARespondent-should-create-adaAllocateFTPAJudge.json
https://tools.hmcts.net/jira/browse/RIA-6964
Added FT for adaAllocateFTPAJudge suitable task
```
[ ] Yes
[ x ] No
```
=> RIA-6964 Added FT for adaAllocateFTPAJudge suitable task

Jenkinsfile_CNP, Jenkinsfile_nightly, src/functionalTest/resources/scenarios/ia/IA-RIA-6469-requestFeeRemission-should-create-reviewRemissionApplication-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6469-submit-application-with-remission-and-appealSubmitted-postEventState-should-create-reviewRemissionApplication-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6469-submit-application-with-remission-and-pendingPayment-postEventState-should-create-reviewRemissionApplication-task.json, src/functionalTest/resources/scenarios/ia/IA-RWA-000-customiseHearingBundle-with-finalBundling-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RWA-000-generateHearingBundle-with-finalBundling-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RWA-000-prepareForHearing-postEventState-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RWA-000-submitAppeal-with-appealSubmitted-postEventState-should-create-a-task.json, src/testUtils/java/uk/gov/hmcts/reform/wapostdeploymentfttests/services/AuthorizationHeadersProvider.java
https://tools.hmcts.net/jira/browse/RIA-6469
Added review remission application task ft tests
```
[ ] Yes
[ x ] No
```
=> Ria 6469 review remission application ft tests v2

src/functionalTest/resources/scenarios/ia/IA-RIA-6474-applyForFTPAAppellant-should-create-assignAFTPAJudge-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-6474-applyForFTPARespondent-should-create-assignAFTPAJudge-task.json
https://tools.hmcts.net/jira/browse/RIA-6474
Added assign aftpa judge task ft tests
```
[ ] Yes
[ x ] No
```
=> Ria 6474 assign aftpa judge ft tests v2

src/functionalTest/resources/scenarios/ia/IA-RIA-6473-reviewHearingRequirements-should-create-listTheCase-task.json
https://tools.hmcts.net/jira/browse/RIA-6473
Added ctsc list the case ft tests
```
[ ] Yes
[ x ] No
```
=> RIA-6473 Added functional tests for List the case task

src/functionalTest/resources/scenarios/ia/IA-RIA-6471-recordRemissionDecision-should-create-sendPaymentRequest-task.json
https://tools.hmcts.net/jira/browse/RIA-6471
Added ctsc send payment request ft tests
```
[ ] Yes
[  x ] No
```
=> RIA-6471 Added functional tests for send payment request task

.github/renovate.json, build.gradle, src/functionalTest/resources/scenarios/ia/IA-RIA-7843-decide-an-application-with-adjourn-application-granted-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-7843-decide-an-application-with-expedite-application-granted-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-7843-decide-an-application-with-transfer-application-granted-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-7843
Added functional tests for editCaseListing
```
[ ] Yes
[ x ] No
```
=> RIA-7843 Added functional tests for editCaseListing

.github/renovate.json, build.gradle, src/functionalTest/resources/scenarios/ia/IA-RIA-7454-ejp-transfer-down-notification-on-makeAnApplication-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-7454-ejp-transfer-down-notification-on-submitAppeal-with-appealSubmitted-postEventState-should-create-a-task.json, src/functionalTest/resources/templates/ia/ccd/minimal-appeal-started-internal.json
https://tools.hmcts.net/jira/browse/RIA-7454
Added functional tests for EJP transfer down notifications (isNotificationTurned off = null)
```
[ ] Yes
[ x ] No
```
=> RIA-7454 Added functional tests for EJP transfer down notifications

src/functionalTest/resources/scenarios/ia/IA-RIA-7453-ejp-transfer-down-submitAppeal-with-appealSubmitted-postEventState-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-7453
Added functional test for EJP transfer down case creation task
```
[ ] Yes
[ x ] No
```
=> RIA-7453 functional test for EJP transfer down case creation task

config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/ia/IA-RIA-6933-adaSuitabilityReview-with-prepareForHearing-postEventState-should-create-a-task.json, src/functionalTest/resources/templates/ia/ccd/minimal-appeal-started-ada.json
https://tools.hmcts.net/jira/browse/RIA-6933
Added FT for adaSuitabilityReview suitable task
```
[ ] Yes
[ x ] No
```
=> Ria 6933 ada suitability review suitable ft

src/functionalTest/resources/scenarios/ia/IA-RIA-8034-create-task-when-CMR-is-listed.json
https://tools.hmcts.net/jira/browse/RIA-8034
```
[ ] Yes
[x ] No
```
=> RIA-8034 - Create work allocation task when CMR is listed

src/functionalTest/resources/scenarios/ia/IA-RIA-8034-create-task-when-CMR-is-listed.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8035-handle-cmr-updated-notification-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-8035
RIA-8035 Add handleCmrUpdated test event
=> RIA-8035 Add triggerCmrUpdated test event

src/functionalTest/resources/scenarios/ia/IA-RIA-8034-create-send-cmr-notification-task-when-CMR-is-listed.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8035-handle-cmr-updated-notification-should-create-a-task.json
=> RIA-8035 RIA-8035 : Added CTSC admin and team leader permissions

src/functionalTest/resources/scenarios/ia/IA-RIA-7793-handle-hearing-exception-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-7793
Added functional test for handleHearingException event
```
[ ] Yes
[ x ] No
```
=> RIA-7793 Added functional test for handleHearingException event

.github/renovate.json, build.gradle, src/functionalTest/resources/scenarios/ia/IA-RIA-7636-case-is-auto-updated-or-cancelled-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-7778-decisionAndReasonsStarted-with-listCaseHearingCentre-should-create-listTheCase-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-7790-recordAdjournmentDetails-with-hearingAdjournmentWhen-and-relistCaseImmediately-should-create-listTheCase-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-7793-handle-hearing-exception-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-7843-decide-an-application-with-adjourn-application-granted-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-7843-decide-an-application-with-expedite-application-granted-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-7843-decide-an-application-with-transfer-application-granted-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8034-create-send-cmr-notification-task-when-CMR-is-listed.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8034-create-task-when-CMR-is-listed.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8035-handle-cmr-updated-notification-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RWA-000-prepareForHearing-postEventState-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-7636
```
[ ] Yes
[x ] No
```
=> RIA-7636 - WA task to review interpreter details when case is auto updated or cancelled

src/functionalTest/resources/scenarios/ia/IA-RIA-7778-decisionAndReasonsStarted-with-listCaseHearingCentre-isIntegrated-should-create-listTheCase-task.json
https://tools.hmcts.net/jira/browse/RIA-8417
- Updated the functional test of "listTheCase" WA task when trigger "decisionAndReasonsStarted" event
```
[ ] Yes
[X] No
```
=> RIA-8417 list the case-wa task issues

src/functionalTest/resources/scenarios/ia/IA-RIA-7843-decide-an-application-with-expedite-application-granted-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8179-handle-restore-state-from-adjourn-should-create-a-task-when-is-integrated.json
https://tools.hmcts.net/jira/browse/RIA-8391
RIA-8391 Modify isIntegrated from Boolean to Yes/No
```
[ ] Yes
[X] No
```
=> RIA-8391 Modify isIntegrated from Boolean to Yes/No

src/functionalTest/resources/scenarios/ia/IA-RIA-7735-apply-for-costs-with-decide-a-costs-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-7735
Added FT for 'reviewCosts' TASK
```
[ ] Yes
[ ] No
```
=> RIA-7735 apply_for_costs

src/functionalTest/resources/scenarios/ia/IA-RIA-7778-RIA-7985-decisionAndReasonsStarted-with-listCaseHearingCentre-isIntegrated-disabled-autoHearingRequestEnabled-should-create-listTheCase-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-7985-listCaseWithoutHearingRequirements-with-disabled-autoHearingRequestEnabled-should-create-listTheCase-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-7985-listCaseWithoutHearingRequirements-with-non-integrated-enabled-autoHearingRequestEnabled-should-create-listTheCase-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-7985-reviewHearingRequirements-with-disabled-autoHearingRequestEnabled-should-create-listTheCase-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-7985-reviewHearingRequirements-with-enabled-autoHearingRequestEnabled-non-integrated-should-create-listTheCase-task.json
- update the functional test from true/false to Yes/No for the "reviewHearingRequirements", "listCaseWithoutHearingRequirements" and "decisionAndReasonsStarted" event
```
[ ] Yes
[X] No
```
=> RIA-7985-list-the-case-work-allocation-task-is-not-created-for-List-Assist-hearing-requests-2

src/functionalTest/resources/scenarios/ia/IA-RIA-8231-listCaseWithoutHearingRequirements-with-panel-required-should-create-listTheCase-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8231-reviewHearingRequirements-with-panel-required-should-create-listTheCase-task.json
[RIA-8231](https://tools.hmcts.net/jira/browse/RIA-8231)
- Trigger `listTheCase` when `isPanelRequired` and `isIntegrated` are both true during `reviewHearingRequirements` and `listCaseWithoutHearingRequirements`
```
[ ] Yes
[x] No
```
=> RIA-8231 ListTheCase when panel is required

src/functionalTest/resources/scenarios/ia/IA-RIA-8292-decideAnApplication-with-rule-31-32-granted-should-create-a-followUpSetAsideDecision-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8292-makeAnApplication-with-rule-31-32-should-create-a-reviewSetAsideDecisionApplication-task.json
https://tools.hmcts.net/jira/browse/RIA-8292
- create reviewSetAsideDecisionApplication task when trigger makeAnApplication event
- create delayed followUpSetAsideDecision task when trigger decideAnApplication event
- create functional test
```
[ ] Yes
[X] No
```
=> RIA-8292 review set aside decision application wa task

src/functionalTest/resources/scenarios/ia/IA-RIA-8294-decideFtpaApplication-appellant-with-rule-35-should-create-a-reviewAppealSetAsideUnderRule35-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8294-decideFtpaApplication-respondent-with-rule-35-should-create-a-reviewAppealSetAsideUnderRule35-task.json
https://tools.hmcts.net/jira/browse/RIA-8294
- create functional test for "reviewAppealSetAsideUnderRule35" WA task (including appellant and respondent)
```
[ ] Yes
[X] No
```
=> RIA-8294 review appeal set aside under rule 35 WA task

src/functionalTest/resources/scenarios/ia/IA-RIA-8295-updateTribunalDecision-with-rule-32-should-create-a-reviewAppealSetAsideUnderRule32-task.json
https://tools.hmcts.net/jira/browse/RIA-8295
- create functional test for "reviewAppealSetAsideUnderRule32" WA task 
```
[ ] Yes
[X] No
```
=> RIA-8295 review appeal set aside under rule 32 WA task

src/functionalTest/resources/scenarios/ia/IA-RIA-8285-markAppealAsRemitted-should-create-reviewRemittedAppeal-task.json
https://tools.hmcts.net/jira/browse/RIA-8290
Added functional test for reviewRemittedAppeal task
```
[ ] Yes
[ x ] No
```
=> RIA-8285 Added functional test for reviewRemittedAppeal task

src/functionalTest/resources/scenarios/ia/IA-RIA-8286-manageFeeUpdate-with-refund-option-should-create-a-processFeeRefund-task.json
https://tools.hmcts.net/jira/browse/RIA-8286
RIA-8286 Process fee refund - WA task
```
[ ] Yes
[x] No
```
=> RIA-8286 Process fee refund - WA task

src/functionalTest/resources/scenarios/ia/IA-RIA-8269-startAppeal-should-create-a-delayed-reviewDraftAppeal-task.json
https://tools.hmcts.net/jira/browse/RIA-8269
Added functional test for reviewDraftAppeal task
```
[ ] Yes
[ x ] No
```
=> RIA-8269 Added functional test for reviewDraftAppeal task

src/functionalTest/resources/scenarios/ia/IA-RIA-8270-requestCaseBuilding-should-create-a-printAndSendHoBundle-task.json, src/testUtils/java/uk/gov/hmcts/reform/wapostdeploymentfttests/services/AuthorizationHeadersProvider.java
https://tools.hmcts.net/jira/browse/RIA-8270
Added functional test for printAndSendHoBundle task
```
[ ] Yes
[ x ] No
```
=> RIA-8270 Added functional test for printAndSendHoBundle task

src/functionalTest/resources/scenarios/ia/IA-RIA-8272-requestResponseReview-should-create-a-printAndSendHoResponse-task.json
https://tools.hmcts.net/jira/browse/RIA-8272
Added printAndSendHoResponse FT
```
[ ] Yes
[ x ] No
```
=> RIA-8272 Added printAndSendHoResponse FT

src/functionalTest/resources/scenarios/ia/IA-RIA-8271-requestHearingRequirements-should-create-a-printAndSendHearingRequerimentsForm-task.json
https://tools.hmcts.net/jira/browse/RIA-8271
Print and send hearing requirements - WA task
```
[ ] Yes
[x] No
```
=> RIA-8271 Print and send hearing requirements - WA task

src/functionalTest/resources/scenarios/ia/IA-RIA-8273-generateHearingBundle-should-create-a-printAndSendHearingBundle-task.json
https://tools.hmcts.net/jira/browse/RIA-8273
Print and send hearing bundle - WA task
```
[ ] Yes
[x] No
```
=> RIA-8273 Print and send hearing bundle - WA task

src/functionalTest/resources/scenarios/ia/IA-RIA-8285-markAppealAsRemitted-should-create-reviewRemittedAppeal-task.json
=> RIA-TASK - REMITTED -> Master: DO NOT MERGE

src/functionalTest/resources/scenarios/ia/IA-RIA-8277-makeAnApplication-should-create-printAndSendHoApplication-task.json
https://tools.hmcts.net/jira/browse/RIA-8277
Added FT for WA task "printAndSendHoApplication"
```
[ ] Yes
[ x ] No
```
=> RIA-8277 Added FT for WA task "printAndSendHoApplication"

src/functionalTest/resources/scenarios/ia/IA-RIA-8270-requestCaseBuilding-should-create-a-printAndSendHoBundle-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8271-requestHearingRequirements-should-create-a-printAndSendHearingRequerimentsForm-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8276-updateTribunalDecision-should-create-printAndSendDecisionCorrectedRule31-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8277-makeAnApplication-should-create-printAndSendHoApplication-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8278-uploadAddendumEvidenceHomeOffice-should-create-printAndSendHoEvidence-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8278-uploadAdditionalEvidenceHomeOffice-should-create-printAndSendHoEvidence-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8296-updateTribunalDecision-should-create-printAndSendDecisionCorrectedRule32-task.json
https://tools.hmcts.net/jira/browse/RIA-8278
Added FT for WA task "printAndSendHoEvidence"
```
[ ] Yes
[ x ] No
```
=> RIA-8277 Added FT for WA task "printAndSendHoEvidence"

src/functionalTest/resources/scenarios/ia/IA-RIA-8274-sendDecisionAndReasons-should-create-printAndSendAppealDecision-task.json
Added WA task "Print and send appeal decision and FTPA form"
Added FT for WA task "printAndSendAppealDecision"
```
[ ] Yes
[ x ] No
```
=> RIA-8274 Added FT for WA task "printAndSendAppealDecision"

src/functionalTest/resources/scenarios/ia/IA-RIA-8275-decideFtpaApplication-should-create-printAndSendFTPADecision-task.json
https://tools.hmcts.net/jira/browse/RIA-8275
Added FT for WA task "printAndSendFTPADecision"
```
[ ] Yes
[ x ] No
```
=> RIA-8275 Added FT for WA task "printAndSendFTPADecision"

src/functionalTest/resources/scenarios/ia/IA-RIA-8271-requestHearingRequirements-should-create-a-printAndSendHearingRequerimentsForm-task.json
https://tools.hmcts.net/jira/browse/RIA-8271
Updated post event state
```
[ ] Yes
[ x ] No
```
=> RIA-8271 Updated post event state

src/functionalTest/resources/scenarios/ia/IA-RIA-8279-requestNewHearingRequirements-should-create-printAndSendReheardHearingRequirements-task.json
https://tools.hmcts.net/jira/browse/RIA-8279
Added FT for WA task "requestNewHearingRequirements"
```
[ ] Yes
[ x ] No
```
=> RIA-8279 Added FT for WA task "requestNewHearingRequirements"

build.gradle, config/checkstyle/checkstyle.xml, src/functionalTest/resources/scenarios/ia/IA-RIA-9144-ariaCreateCase-should-create-a-task.json, src/functionalTest/resources/templates/ia/ccd/minimal-appeal-started.json
https://tools.hmcts.net/jira/browse/RIA-9144
Added FT for reviewMigratedCase task
```
[ ] Yes
[ x ] No
```
=> RIA-9144 Added FT for reviewMigratedCase task

src/functionalTest/resources/scenarios/ia/IA-RIA-9040-updateNextHearingInfo-reconfigure-task.json
**Before creating a pull request make sure that:**
- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] tests have been updated / new tests has been added (if needed)
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/RIA-9040
```
[ ] Yes
[x ] No
```
=> RIA-9040 - add functional test for updateNextHearingInfo event

src/functionalTest/resources/scenarios/ia/IA-RIA-9159-ariaCreateCase-with-remission-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-9159
Added FT for reviewAriaRemissionApplication task
```
[ ] Yes
[ x ] No
```
=> RIA-9159 Added FT for reviewAriaRemissionApplication task

src/functionalTest/resources/scenarios/ia/IA-RIA-9040-updateNextHearingInfo-reconfigure-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-9267-adjounHearingWithoutDate-reconfigure-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-9267-cmrListing-reconfigure-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-9267-cmrReListing-reconfigure-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-9267-hearingCancelled-reconfigure-task.json
https://tools.hmcts.net/jira/browse/RIA-9267
Update the functional tests for WA tasks reconfigure tasks
```
[ ] Yes
[x] No
```
=> RIA-9267 Update the functional tests for WA reconfigure tasks

src/functionalTest/resources/scenarios/ia/IA-RIA-9144-ariaCreateCase-should-create-a-task.json
https://tools.hmcts.net/jira/browse/RIA-8976
Updated work type for reviewMigratedCase task
```
[ ] Yes
[ x ] No
```
=> RIA-8976 Updated work type for reviewMigratedCase task

src/functionalTest/resources/scenarios/ia/IA-RIA-8292-decideAnApplication-with-rule-31-32-granted-should-create-a-followUpSetAsideDecision-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8292-makeAnApplication-with-rule-31-32-should-create-a-reviewSetAsideDecisionApplication-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8294-decideFtpaApplication-appellant-with-rule-35-should-create-a-reviewAppealSetAsideUnderRule35-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8294-decideFtpaApplication-respondent-with-rule-35-should-create-a-reviewAppealSetAsideUnderRule35-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8295-updateTribunalDecision-with-rule-32-should-create-a-reviewAppealSetAsideUnderRule32-task.json
Merge DLRM features to master
```
[ ] Yes
[ x ] No
```
=> RIA-TASK - DLRM -> Master: DO NOT MERGE

src/functionalTest/resources/scenarios/ia/IA-RIA-8285-markAppealAsRemitted-should-create-reviewRemittedAppeal-task.json
=> RIA-TASK - REMITTED -> DLRM: DO NOT MERGE

build.gradle, config/checkstyle/checkstyle.xml, src/functionalTest/resources/scenarios/ia/IA-RIA-9144-ariaCreateCase-should-create-a-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-9159-ariaCreateCase-with-remission-should-create-a-task.json, src/functionalTest/resources/templates/ia/ccd/minimal-appeal-started.json
RIA-TASK - DLRM Migration -> Master: DO NOT MERGE
```
[ ] Yes
[ x ] No
```
=> RIA-TASK - DLRM Migration -> Master: DO NOT MERGE

src/functionalTest/resources/scenarios/ia/IA-RIA-8286-manageFeeUpdate-with-refund-option-should-create-a-processFeeRefund-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8292-decideAnApplication-with-rule-31-32-granted-should-create-a-followUpSetAsideDecision-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8292-makeAnApplication-with-rule-31-32-should-create-a-reviewSetAsideDecisionApplication-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8294-decideFtpaApplication-appellant-with-rule-35-should-create-a-reviewAppealSetAsideUnderRule35-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8294-decideFtpaApplication-respondent-with-rule-35-should-create-a-reviewAppealSetAsideUnderRule35-task.json, src/functionalTest/resources/scenarios/ia/IA-RIA-8295-updateTribunalDecision-with-rule-32-should-create-a-reviewAppealSetAsideUnderRule32-task.json
=> RIA-TASK - REFUND -> Master: DO NOT MERGE
